export const trips: Trip[] = [
  {
    id: "1",
    name: "Trip 1",
    image_url:
      "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    start_date: "2024-11-01",
    end_date: "2024-11-10",
    plans: [
      {
        id: "1",
        plan_type: "lodging",
        name: "Luxury Hotel",
        airline: "Air France",
        checkin_at: "2024-11-01T15:00",
        checkout_at: "2024-11-05T11:00",
        expense: 500,
        address: "Paris, France",
        phone: "0123456789",
        email: "contact@luxuryhotel.com",
        document: "https://example.com/luxury_hotel_invoice.pdf",
      },
      {
        id: "2",
        plan_type: "flight",
        name: "abc",
        airline: "VN Airline",
        departure_at: "2024-11-01T10:00",
        departure_address: "New York - JFK Airport",
        departure_terminal: "C",
        departure_gate: "32",
        seat: "12A",
        coach: "Business",
        arrival_at: "2024-11-01T18:00",
        arrival_address: "Paris - Charles de Gaulle",
        arrival_terminal: "2E",
        arrival_gate: "14",
        expense: 1000,
        document: "https://example.com/flight_ticket.pdf",
      },
      {
        id: "3",
        plan_type: "restaurant",
        name: "Le Gourmet",
        start_at: "2024-11-02T20:00",
        expense: 150,
        address: "Paris, France",
        phone: "0987654321",
        email: "info@legourmet.fr",
        document: "https://example.com/dinner_invoice.pdf",
      },
    ],
  },
  {
    id: "2",
    name: "Trip 2",
    image_url:
      "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
    start_date: "2024-12-05",
    end_date: "2024-12-12",
    plans: [
      {
        id: "4",
        plan_type: "lodging",
        name: "Mountain Resort",
        airline: "Thai Airways",
        checkin_at: "2024-12-05T14:00",
        checkout_at: "2024-12-09T10:00",
        expense: 600,
        address: "Chiang Mai, Thailand",
        phone: "0987654321",
        email: "contact@mountainresort.com",
        document: "https://example.com/resort_invoice.pdf",
      },
      {
        id: "5",
        plan_type: "tour",
        name: "Elephant Sanctuary Tour",
        start_at: "2024-12-06T09:00",
        end_at: "2024-12-06T17:00",
        expense: 120,
        address: "Chiang Mai, Thailand",
        phone: "0123456789",
        email: "info@elephanttour.com",
        document: "https://example.com/tour_ticket.pdf",
      },
      {
        id: "6",
        plan_type: "boat",
        name: "River Cruise",
        coach: "A",
        seat: "14",
        departure_at: "2024-12-07T10:00",
        departure_address: "Chiang Mai River",
        arrival_at: "2024-12-07T12:00",
        arrival_address: "Chiang Mai River",
        expense: 200,
        document: "https://example.com/boat_ticket.pdf",
      },
    ],
  },
  {
    id: "3",
    name: "Trip 3",
    image_url:
      "https://i0.wp.com/picjumbo.com/wp-content/uploads/wooden-pier-free-image.jpeg?w=600&quality=80",
    start_date: "2025-01-10",
    end_date: "2025-01-20",
    plans: [
      {
        name: "",
        id: "7",
        plan_type: "flight",
        airline: "Vietjet",
        departure_at: "2025-01-10T07:00",
        departure_address: "Los Angeles - LAX",
        departure_terminal: "B",
        departure_gate: "20",
        seat: "15C",
        coach: "Economy",
        arrival_at: "2025-01-10T11:00",
        arrival_address: "Tokyo - Narita Airport",
        arrival_terminal: "1",
        arrival_gate: "10",
        expense: 900,
        document: "https://example.com/flight_ticket.pdf",
      },
      {
        id: "8",
        plan_type: "carRental",
        name: "",
        rental_agency: "Tokyo Car Rentals",
        pickup_at: "2025-01-11T09:00",
        pickup_address: "Tokyo Narita Airport",
        pickup_phone: "0123456789",
        drop_off_at: "2025-01-15T18:00",
        drop_off_addrress: "Tokyo Narita Airport",
        drop_off_phone: "0123456789",
        expense: 300,
        document: "https://example.com/car_rental_receipt.pdf",
      },
      {
        id: "9",
        plan_type: "shopping",
        name: "Akihabara Electronics",
        start_at: "2025-01-13T12:00",
        end_at: "2025-01-13T16:00",
        expense: 400,
        address: "Akihabara, Tokyo",
        phone: "0987654321",
        email: "sales@akihabara.com",
        document: "https://example.com/shopping_invoice.pdf",
      },
    ],
  },
];